fix rad recipe register (#5204)
# Description

The PR is a a temporary fix for registering command on the server side
using bicep that has the same name as that of devrecipe

#### CLI Test Result:
```
pratiksm@Pratikshyas-MacBook-Pro radius % rad recipe list
NAME              TYPE                              TEMPLATE
mongo-azure       Applications.Link/mongoDatabases  radius.azurecr.io/recipes/mongodatabases/azure:1.0
redis-kubernetes  Applications.Link/redisCaches     radius.azurecr.io/recipes/rediscaches/kubernetes:1.0
pratiksm@Pratikshyas-MacBook-Pro radius % rad recipe register --name mongo-azure -e myenv -w kind-kind  --template-path radiusdev.azurecr.io/recipes/functionaltest/parameters/mongodatabases/azure:1.0 --link-type Applications.Link/mongoDatabases
Error: recipe with name "mongo-azure" already exists in the environment "myenv"
pratiksm@Pratikshyas-MacBook-Pro radius % rad recipe register --name mongo -e myenv -w kind-kind  --template-path radiusdev.azurecr.io/recipes/functionaltest/parameters/mongodatabases/azure:1.0 --link-type Applications.Link/mongoDatabases
Successfully linked recipe "mongo" to environment "myenv"
pratiksm@Pratikshyas-MacBook-Pro radius % rad recipe list
NAME              TYPE                              TEMPLATE
mongo             Applications.Link/mongoDatabases  radiusdev.azurecr.io/recipes/functionaltest/parameters/mongodatabases/azure:1.0
mongo-azure       Applications.Link/mongoDatabases  radius.azurecr.io/recipes/mongodatabases/azure:1.0
redis-kubernetes  Applications.Link/redisCaches     radius.azurecr.io/recipes/rediscaches/kubernetes:1.0
```
#### Bicep test result
Bicep Content
```
resource env 'Applications.Core/environments@2022-03-15-privatepreview' = {
  name: 'corerp-resources-environment-env'
  location: location
  properties: {
    compute: {
      kind: 'kubernetes'
      resourceId: 'self'
      namespace: 'corerp-resources-environment-env'
    }
    recipes: {
      recipe1: {
          linkType: 'Applications.Link/mongoDatabases'
          templatePath: 'testpublicrecipe.azurecr.io/bicep/modules/mongodatabases:v1'
      }
    }
    useDevRecipes: true
  }
}
```

```
pratiksm@Pratikshyas-MacBook-Pro radius % rad deploy /Users/pratiksm/Documents/MyGoWorkSpace/src/project-radius/radius/test/functional/corerp/resources/testdata/corerp-resources-environment.bicep
Building /Users/pratiksm/Documents/MyGoWorkSpace/src/project-radius/radius/test/functional/corerp/resources/testdata/corerp-resources-environment.bicep...
Deploying template '/Users/pratiksm/Documents/MyGoWorkSpace/src/project-radius/radius/test/functional/corerp/resources/testdata/corerp-resources-environment.bicep' for application 'radius' and environment 'myenv' from workspace 'kind-kind'...

Deployment In Progress...

Completed            corerp-resources-environment-env Applications.Core/environments

Deployment Complete

Resources:
    corerp-resources-environment-env Applications.Core/environments
pratiksm@Pratikshyas-MacBook-Pro radius % rad env switch corerp-resources-environment-env
Switching default environment from myenv to corerp-resources-environment-env
Successfully wrote configuration to /Users/pratiksm/.rad/config.yaml
pratiksm@Pratikshyas-MacBook-Pro radius % rad recipe list
NAME              TYPE                              TEMPLATE
recipe1           Applications.Link/mongoDatabases  testpublicrecipe.azurecr.io/bicep/modules/mongodatabases:v1
redis-kubernetes  Applications.Link/redisCaches     radius.azurecr.io/recipes/rediscaches/kubernetes:1.0
mongo-azure       Applications.Link/mongoDatabases  radius.azurecr.io/recipes/mongodatabases/azure:1.0

```
## Issue reference

<!--
We strive to have all PR being opened based on an issue, where the
problem or feature have been discussed prior to implementation.
-->

Fixes: #issue_number

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of
the following list:

* [x] Code compiles correctly
* [ ] Adds necessary unit tests for change
* [ ] Adds necessary E2E tests for change
* [x] Unit tests passing
* [ ] Extended the documentation / Created issue for it

(cherry picked from commit 35725226b2fed076697ce38559133d6b9d7476d0)