Do not fail for codecov error (#7429)
# Description

Tokenless upload (forked repo pr) can be throttled like below. This is
to unblock the build even if codecov is failed.

```
==> Uploader SHASUM verified (e3ea28a069fe174eb99ac2ffb523bfb55d5d29a7cfd93ef48cde12e9b552b492  codecov)
info - 2024-04-02 16:12:29,890 -- ci service found: github-actions
debug - 2024-04-02 16:12:29,893 -- versioning system found: <class 'codecov_cli.helpers.versioning_systems.GitVersioningSystem'>
debug - 2024-04-02 16:12:29,893 -- Loading config from .codecov.yml
debug - 2024-04-02 16:12:29,895 -- Starting create commit process --- {"commit_sha": "babae5be5a94d[64](https://github.com/radius-project/radius/actions/runs/8525878516/job/23353867349?pr=7390#step:7:65)fd7976b80e94905255116e920", "parent_sha": null, "pr": "7390", "branch": "vishwahiremat/recipe_show_cmd", "slug": "radius-project/radius", "token": null, "service": "github", "enterprise_url": null}
info - 2024-04-02 16:12:30,144 -- The PR is happening in a forked repo. Using tokenless upload.
info - 2024-04-02 16:12:30,334 -- Process Commit creating complete
debug - 2024-04-02 16:12:30,334 -- Commit creating result --- {"result": "RequestResult(error=RequestError(code='HTTP Error 429', params={}, description='{\"detail\":\"Tokenless has reached GitHub rate limit. Please upload using a token: https://docs.codecov.com/docs/adding-the-codecov-token. Expected available in 1188 seconds.\"}'), warnings=[], status_code=429, text='{\"detail\":\"Tokenless has reached GitHub rate limit. Please upload using a token: https://docs.codecov.com/docs/adding-the-codecov-token. Expected available in 1188 seconds.\"}')"}
error - 2024-04-02 16:12:30,334 -- Commit creating failed: {"detail":"Tokenless has reached GitHub rate limit. Please upload using a token: https://docs.codecov.com/docs/adding-the-codecov-token. Expected available in 1188 seconds."}
Error: Codecov: Failed to properly create commit: The process '/home/runner/work/_actions/codecov/codecov-action/v4/dist/codecov' failed with exit code 1
```

## Type of change

<!--

Please select **one** of the following options that describes your
change and delete the others. Clearly identifying the type of change you
are making will help us review your PR faster, and is used in authoring
release notes.

If you are making a bug fix or functionality change to Radius and do not
have an associated issue link please create one now.

-->

- This pull request fixes a bug in Radius and has an approved issue
(issue link required).
- This pull request adds or changes features of Radius and has an
approved issue (issue link required).
- This pull request is a minor refactor, code cleanup, test improvement,
or other maintenance task and doesn't change the functionality of Radius
(issue link optional).

<!--

Please update the following to link the associated issue. This is
required for some kinds of changes (see above).

-->

Fixes: #issue_number

Signed-off-by: Young Bu Park <youngp@microsoft.com>