Remove helm chart uploads to ACR  (#8565)
# Description

We push Radius helm charts on merges to main to GHCR and ACR. We only
need to push to GHCR. The ACR commands that we use are deprecated,
causing errors in the helm chart upload. See below:

```
Run az acr helm push --name radius ./dist/Charts/helm/radius-0.42.42-dev.tgz --force
WARNING: This command has been deprecated and will be removed in future release. Use 'Helm v3 commands' instead. Learn more about storing Helm charts at https://aka.ms/acr/helm
WARNING: This command is implicitly deprecated because command group 'acr helm' is deprecated and will be removed in a future release. Use 'Helm v3 commands' instead.
ERROR: 2025-02-18 [21](https://github.com/radius-project/radius/actions/runs/13400072813/job/37428811515#step:9:22):13:31.102149 Error: The operation is disallowed on this registry, repository or image. View troubleshooting steps at https://aka.ms/acr/faq/#why-does-my-pull-or-push-request-fail-with-disallowed-operation-.
```

This change removes the upload to ACR

## Type of change

<!--

Please select **one** of the following options that describes your
change and delete the others. Clearly identifying the type of change you
are making will help us review your PR faster, and is used in authoring
release notes.

If you are making a bug fix or functionality change to Radius and do not
have an associated issue link please create one now.

-->

- This pull request is a minor refactor, code cleanup, test improvement,
or other maintenance task and doesn't change the functionality of Radius
(issue link optional).

<!--

Please update the following to link the associated issue. This is
required for some kinds of changes (see above).

-->

Fixes: #issue_number

## Contributor checklist
Please verify that the PR meets the following requirements, where
applicable:

- An overview of proposed schema changes is included in a linked GitHub
issue.
    - [ ] Yes
    - [x] Not applicable
- A design document PR is created in the [design-notes
repository](https://github.com/radius-project/design-notes/), if new
APIs are being introduced.
    - [ ] Yes
    - [x] Not applicable
- The design document has been reviewed and approved by Radius
maintainers/approvers.
    - [ ] Yes
    - [x] Not applicable
- A PR for the [samples
repository](https://github.com/radius-project/samples) is created, if
existing samples are affected by the changes in this PR.
    - [ ] Yes
    - [x] Not applicable
- A PR for the [documentation
repository](https://github.com/radius-project/docs) is created, if the
changes in this PR affect the documentation or any user facing updates
are made.
    - [ ] Yes
    - [ ] Not applicable
- A PR for the [recipes
repository](https://github.com/radius-project/recipes) is created, if
existing recipes are affected by the changes in this PR.
    - [ ] Yes
    - [x] Not applicable

Signed-off-by: sk593 <shruthikumar@microsoft.com>